name: MiKit
version: 1.0
main: com.slaratro.MiKit
api-version: 1.21 # Cambia esto según tu versión de Minecraft (ej. 1.18, 1.21)
authors: [slaratro]

commands:
  kit:
    description: Te entrega un kit de inicio
    usage: /kit